import type { Metadata } from 'next';

// These styles apply to every route in the application
import '@/app/globals.css';

// Initialize firebase app
require('@/utils/firebase');

export const metadata: Metadata = {
  title: 'sanchezyspace Next.js Template',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
